package g3.hibernate.entity.ver2;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Browser generated by hbm2java
 */
public class Browser  implements java.io.Serializable {


     private int id;
     private String title;
     private int parentId;
     private String querySearch;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Browser() {
    }

    public Browser(int id, String title, int parentId, String querySearch, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.title = title;
       this.parentId = parentId;
       this.querySearch = querySearch;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }
    public String getQuerySearch() {
        return this.querySearch;
    }
    
    public void setQuerySearch(String querySearch) {
        this.querySearch = querySearch;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


