package g3.hibernate.entity.ver2;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private int id;
     private String title;
     private String description;
     private String queryReport;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Report() {
    }

	
    public Report(int id, String title, String queryReport, boolean isDeleted) {
        this.id = id;
        this.title = title;
        this.queryReport = queryReport;
        this.isDeleted = isDeleted;
    }
    public Report(int id, String title, String description, String queryReport, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.title = title;
       this.description = description;
       this.queryReport = queryReport;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getQueryReport() {
        return this.queryReport;
    }
    
    public void setQueryReport(String queryReport) {
        this.queryReport = queryReport;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


