package g3.hibernate.entity;
// Generated May 23, 2013 2:18:11 PM by Hibernate Tools 3.2.1.GA



/**
 * AlbumMusicMapping generated by hbm2java
 */
public class AlbumMusicMapping  implements java.io.Serializable {


     private AlbumMusicMappingId id;
     private Integer trackNumber;

    public AlbumMusicMapping() {
    }

	
    public AlbumMusicMapping(AlbumMusicMappingId id) {
        this.id = id;
    }
    public AlbumMusicMapping(AlbumMusicMappingId id, Integer trackNumber) {
       this.id = id;
       this.trackNumber = trackNumber;
    }
   
    public AlbumMusicMappingId getId() {
        return this.id;
    }
    
    public void setId(AlbumMusicMappingId id) {
        this.id = id;
    }
    public Integer getTrackNumber() {
        return this.trackNumber;
    }
    
    public void setTrackNumber(Integer trackNumber) {
        this.trackNumber = trackNumber;
    }




}


