package g3.hibernate.entity;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA



/**
 * AlbumMusicMapping generated by hbm2java
 */
public class AlbumMusicMapping  implements java.io.Serializable {


     private AlbumMusicMappingId id;
     private int trackNumber;

    public AlbumMusicMapping() {
    }

    public AlbumMusicMapping(AlbumMusicMappingId id, int trackNumber) {
       this.id = id;
       this.trackNumber = trackNumber;
    }
   
    public AlbumMusicMappingId getId() {
        return this.id;
    }
    
    public void setId(AlbumMusicMappingId id) {
        this.id = id;
    }
    public int getTrackNumber() {
        return this.trackNumber;
    }
    
    public void setTrackNumber(int trackNumber) {
        this.trackNumber = trackNumber;
    }




}


