package g3.hibernate.entity;
// Generated May 23, 2013 2:18:11 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Artist generated by hbm2java
 */
public class Artist  implements java.io.Serializable {


     private int id;
     private Serializable name;
     private Serializable details;
     private Serializable workAs;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Artist() {
    }

	
    public Artist(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public Artist(int id, Serializable name, Serializable details, Serializable workAs, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.name = name;
       this.details = details;
       this.workAs = workAs;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getDetails() {
        return this.details;
    }
    
    public void setDetails(Serializable details) {
        this.details = details;
    }
    public Serializable getWorkAs() {
        return this.workAs;
    }
    
    public void setWorkAs(Serializable workAs) {
        this.workAs = workAs;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


