package g3.hibernate.entity.ver2;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA



/**
 * BillDetail generated by hbm2java
 */
public class BillDetail  implements java.io.Serializable {


     private BillDetailId id;
     private Double price;
     private Integer quantity;

    public BillDetail() {
    }

	
    public BillDetail(BillDetailId id) {
        this.id = id;
    }
    public BillDetail(BillDetailId id, Double price, Integer quantity) {
       this.id = id;
       this.price = price;
       this.quantity = quantity;
    }
   
    public BillDetailId getId() {
        return this.id;
    }
    
    public void setId(BillDetailId id) {
        this.id = id;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


