package g3.hibernate.entity;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA



/**
 * BillDetailId generated by hbm2java
 */
public class BillDetailId  implements java.io.Serializable {


     private int billId;
     private int dvdId;

    public BillDetailId() {
    }

    public BillDetailId(int billId, int dvdId) {
       this.billId = billId;
       this.dvdId = dvdId;
    }
   
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public int getDvdId() {
        return this.dvdId;
    }
    
    public void setDvdId(int dvdId) {
        this.dvdId = dvdId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BillDetailId) ) return false;
		 BillDetailId castOther = ( BillDetailId ) other; 
         
		 return (this.getBillId()==castOther.getBillId())
 && (this.getDvdId()==castOther.getDvdId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBillId();
         result = 37 * result + this.getDvdId();
         return result;
   }   


}


