package g3.hibernate.entity;
// Generated May 23, 2013 8:04:27 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int id;
     private int memberId;
     private int productId;
     private Date submittedDate;
     private Serializable commentText;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Comment() {
    }

	
    public Comment(int id, int memberId, int productId, boolean isDeleted) {
        this.id = id;
        this.memberId = memberId;
        this.productId = productId;
        this.isDeleted = isDeleted;
    }
    public Comment(int id, int memberId, int productId, Date submittedDate, Serializable commentText, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.memberId = memberId;
       this.productId = productId;
       this.submittedDate = submittedDate;
       this.commentText = commentText;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Date getSubmittedDate() {
        return this.submittedDate;
    }
    
    public void setSubmittedDate(Date submittedDate) {
        this.submittedDate = submittedDate;
    }
    public Serializable getCommentText() {
        return this.commentText;
    }
    
    public void setCommentText(Serializable commentText) {
        this.commentText = commentText;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


