package g3.hibernate.entity;
// Generated Jun 5, 2013 7:27:49 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Dvd generated by hbm2java
 */
public class Dvd  implements java.io.Serializable {


     private int id;
     private String title;
     private Date releaseDate;
     private String genres;
     private String description;
     private Double price;
     private String imgCover;
     private String author;
     private Integer producerId;
     private Integer supplierId;
     private Integer discNumber;
     private Integer trailerId;
     private Integer albumId;
     private String type;
     private String details;
     private Integer ratePoint;
     private Integer rateCount;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Dvd() {
    }

	
    public Dvd(int id, String title, String imgCover, String author, String type, Date createdDate, Date modifiedDate, boolean isDeleted) {
        this.id = id;
        this.title = title;
        this.imgCover = imgCover;
        this.author = author;
        this.type = type;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.isDeleted = isDeleted;
    }
    public Dvd(int id, String title, Date releaseDate, String genres, String description, Double price, String imgCover, String author, Integer producerId, Integer supplierId, Integer discNumber, Integer trailerId, Integer albumId, String type, String details, Integer ratePoint, Integer rateCount, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.title = title;
       this.releaseDate = releaseDate;
       this.genres = genres;
       this.description = description;
       this.price = price;
       this.imgCover = imgCover;
       this.author = author;
       this.producerId = producerId;
       this.supplierId = supplierId;
       this.discNumber = discNumber;
       this.trailerId = trailerId;
       this.albumId = albumId;
       this.type = type;
       this.details = details;
       this.ratePoint = ratePoint;
       this.rateCount = rateCount;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    public String getGenres() {
        return this.genres;
    }
    
    public void setGenres(String genres) {
        this.genres = genres;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImgCover() {
        return this.imgCover;
    }
    
    public void setImgCover(String imgCover) {
        this.imgCover = imgCover;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public Integer getDiscNumber() {
        return this.discNumber;
    }
    
    public void setDiscNumber(Integer discNumber) {
        this.discNumber = discNumber;
    }
    public Integer getTrailerId() {
        return this.trailerId;
    }
    
    public void setTrailerId(Integer trailerId) {
        this.trailerId = trailerId;
    }
    public Integer getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Integer getRatePoint() {
        return this.ratePoint;
    }
    
    public void setRatePoint(Integer ratePoint) {
        this.ratePoint = ratePoint;
    }
    public Integer getRateCount() {
        return this.rateCount;
    }
    
    public void setRateCount(Integer rateCount) {
        this.rateCount = rateCount;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


