package g3.hibernate.entity;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;

/**
 * Manage generated by hbm2java
 */
public class Manage implements java.io.Serializable {

    private int id;
    private String name;
    private String password;
    private String info;
    private int position;
    private Date newLogin;
    private Date lastLogin;
    private Date createdDate;
    private Date modifiedDate;
    private boolean isLock;

    public Manage() {
    }

    public Manage(int id, String name, String password, int position, Date createdDate, Date modifiedDate, boolean isLock) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.position = position;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.isLock = isLock;
    }

    public Manage(int id, String name, String password, String info, int position, Date newLogin, Date lastLogin, Date createdDate, Date modifiedDate, boolean isLock) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.info = info;
        this.position = position;
        this.newLogin = newLogin;
        this.lastLogin = lastLogin;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.isLock = isLock;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getInfo() {
        return this.info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public Date getNewLogin() {
        return newLogin;
    }

    public void setNewLogin(Date newLogin) {
        this.newLogin = newLogin;
    }

    public Date getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public boolean isIsLock() {
        return this.isLock;
    }

    public void setIsLock(boolean isLock) {
        this.isLock = isLock;
    }
}
