package g3.hibernate.entity.ver2;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA



/**
 * ManagePermissionMappingId generated by hbm2java
 */
public class ManagePermissionMappingId  implements java.io.Serializable {


     private int manageId;
     private int permissionId;

    public ManagePermissionMappingId() {
    }

    public ManagePermissionMappingId(int manageId, int permissionId) {
       this.manageId = manageId;
       this.permissionId = permissionId;
    }
   
    public int getManageId() {
        return this.manageId;
    }
    
    public void setManageId(int manageId) {
        this.manageId = manageId;
    }
    public int getPermissionId() {
        return this.permissionId;
    }
    
    public void setPermissionId(int permissionId) {
        this.permissionId = permissionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ManagePermissionMappingId) ) return false;
		 ManagePermissionMappingId castOther = ( ManagePermissionMappingId ) other; 
         
		 return (this.getManageId()==castOther.getManageId())
 && (this.getPermissionId()==castOther.getPermissionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getManageId();
         result = 37 * result + this.getPermissionId();
         return result;
   }   


}


