package g3.hibernate.entity;
// Generated May 23, 2013 8:04:27 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String password;
     private Date joinedDate;
     private Date modifiedDate;
     private boolean isLock;

    public Member() {
    }

	
    public Member(int id, boolean isLock) {
        this.id = id;
        this.isLock = isLock;
    }
    public Member(int id, String name, String email, String password, Date joinedDate, Date modifiedDate, boolean isLock) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
       this.joinedDate = joinedDate;
       this.modifiedDate = modifiedDate;
       this.isLock = isLock;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsLock() {
        return this.isLock;
    }
    
    public void setIsLock(boolean isLock) {
        this.isLock = isLock;
    }




}


