package g3.hibernate.entity;
// Generated May 23, 2013 8:04:27 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private int id;
     private Serializable title;
     private Serializable studio;
     private Serializable cast;
     private Serializable crew;
     private Integer trailerId;
     private byte[] runtime;
     private Serializable language;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Movie() {
    }

	
    public Movie(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public Movie(int id, Serializable title, Serializable studio, Serializable cast, Serializable crew, Integer trailerId, byte[] runtime, Serializable language, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.title = title;
       this.studio = studio;
       this.cast = cast;
       this.crew = crew;
       this.trailerId = trailerId;
       this.runtime = runtime;
       this.language = language;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Serializable getStudio() {
        return this.studio;
    }
    
    public void setStudio(Serializable studio) {
        this.studio = studio;
    }
    public Serializable getCast() {
        return this.cast;
    }
    
    public void setCast(Serializable cast) {
        this.cast = cast;
    }
    public Serializable getCrew() {
        return this.crew;
    }
    
    public void setCrew(Serializable crew) {
        this.crew = crew;
    }
    public Integer getTrailerId() {
        return this.trailerId;
    }
    
    public void setTrailerId(Integer trailerId) {
        this.trailerId = trailerId;
    }
    public byte[] getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(byte[] runtime) {
        this.runtime = runtime;
    }
    public Serializable getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Serializable language) {
        this.language = language;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


