package g3.hibernate.entity;
// Generated May 23, 2013 2:18:11 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int id;
     private Date orderDate;
     private BigDecimal total;
     private Short status;
     private Serializable customerName;
     private Serializable deliveryAddress;
     private String phone;
     private Serializable message;
     private Integer memberId;
     private boolean isDeleted;

    public Order() {
    }

	
    public Order(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public Order(int id, Date orderDate, BigDecimal total, Short status, Serializable customerName, Serializable deliveryAddress, String phone, Serializable message, Integer memberId, boolean isDeleted) {
       this.id = id;
       this.orderDate = orderDate;
       this.total = total;
       this.status = status;
       this.customerName = customerName;
       this.deliveryAddress = deliveryAddress;
       this.phone = phone;
       this.message = message;
       this.memberId = memberId;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Serializable getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(Serializable customerName) {
        this.customerName = customerName;
    }
    public Serializable getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(Serializable deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Serializable getMessage() {
        return this.message;
    }
    
    public void setMessage(Serializable message) {
        this.message = message;
    }
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


