package g3.hibernate.entity;
// Generated May 23, 2013 2:18:11 PM by Hibernate Tools 3.2.1.GA



/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId  implements java.io.Serializable {


     private int orderId;
     private int productId;

    public OrderDetailId() {
    }

    public OrderDetailId(int orderId, int productId) {
       this.orderId = orderId;
       this.productId = productId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


