package g3.hibernate.entity;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

    private int id;
    private String title;
    private String description;
    private String urlPattern;
    private boolean isBase;
    private int position;
    private Date createdDate;
    private Date modifiedDate;
    private boolean isDeleted;

    public Permission() {
    }

    public Permission(int id, String title, int position, boolean isDeleted) {
        this.id = id;
        this.title = title;
        this.position = position;
        this.isDeleted = isDeleted;
    }

    public Permission(int id, String title, String description, String urlPattern, boolean isBase, int position, Date createdDate, Date modifiedDate, boolean isDeleted) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.urlPattern = urlPattern;
        this.isBase = isBase;
        this.position = position;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.isDeleted = isDeleted;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrlPattern() {
        return this.urlPattern;
    }

    public void setUrlPattern(String urlPattern) {
        this.urlPattern = urlPattern;
    }

    public boolean isIsBase() {
        return isBase;
    }

    public void setIsBase(boolean isBase) {
        this.isBase = isBase;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public boolean isIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}
