package g3.hibernate.entity;
// Generated May 21, 2013 8:59:34 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Song generated by hbm2java
 */
public class Song  implements java.io.Serializable {


     private int id;
     private Serializable title;
     private Integer singerId;
     private Integer composerId;
     private byte[] runtime;
     private Serializable lyrics;
     private boolean isFree;
     private int fileId;
     private Date createdDate;
     private Date modifiedDate;
     private boolean isDeleted;

    public Song() {
    }

	
    public Song(int id, boolean isFree, int fileId, boolean isDeleted) {
        this.id = id;
        this.isFree = isFree;
        this.fileId = fileId;
        this.isDeleted = isDeleted;
    }
    public Song(int id, Serializable title, Integer singerId, Integer composerId, byte[] runtime, Serializable lyrics, boolean isFree, int fileId, Date createdDate, Date modifiedDate, boolean isDeleted) {
       this.id = id;
       this.title = title;
       this.singerId = singerId;
       this.composerId = composerId;
       this.runtime = runtime;
       this.lyrics = lyrics;
       this.isFree = isFree;
       this.fileId = fileId;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.isDeleted = isDeleted;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getTitle() {
        return this.title;
    }
    
    public void setTitle(Serializable title) {
        this.title = title;
    }
    public Integer getSingerId() {
        return this.singerId;
    }
    
    public void setSingerId(Integer singerId) {
        this.singerId = singerId;
    }
    public Integer getComposerId() {
        return this.composerId;
    }
    
    public void setComposerId(Integer composerId) {
        this.composerId = composerId;
    }
    public byte[] getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(byte[] runtime) {
        this.runtime = runtime;
    }
    public Serializable getLyrics() {
        return this.lyrics;
    }
    
    public void setLyrics(Serializable lyrics) {
        this.lyrics = lyrics;
    }
    public boolean isIsFree() {
        return this.isFree;
    }
    
    public void setIsFree(boolean isFree) {
        this.isFree = isFree;
    }
    public int getFileId() {
        return this.fileId;
    }
    
    public void setFileId(int fileId) {
        this.fileId = fileId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


